"""empty message

Revision ID: 2f0f8325cd79
Revises: 232cc9a146fb
Create Date: 2018-06-19 18:37:27.929138

"""

# revision identifiers, used by Alembic.
revision = '2f0f8325cd79'
down_revision = '232cc9a146fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('first', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'first')
    # ### end Alembic commands ###
