"""empty message

Revision ID: 965b44b1b044
Revises: bd0e4be9cfbd
Create Date: 2018-06-19 13:09:17.903017

"""

# revision identifiers, used by Alembic.
revision = '965b44b1b044'
down_revision = 'bd0e4be9cfbd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image', sa.String(), nullable=True))
    op.drop_column('card', 'imgur_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('imgur_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('card', 'image')
    # ### end Alembic commands ###
