"""empty message

Revision ID: bd0e4be9cfbd
Revises: fee9ded638d8
Create Date: 2018-06-19 12:07:47.856165

"""

# revision identifiers, used by Alembic.
revision = 'bd0e4be9cfbd'
down_revision = 'fee9ded638d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('imgur_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'imgur_id')
    # ### end Alembic commands ###
